#!/usr/bin/env python3
"""
Unified data seeding script for LMS.
Creates admin user and inserts all test data (idempotent).
Data is loaded from test_data.json (generated by extract_tests_to_json.py).
Now uses the parsed 'range' and 'unit' fields directly.
Run: python seed_data.py
"""

import os
import sys
import json
from dotenv import load_dotenv

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database import create_tables, SessionLocal
import crud
from models import TestCategory, Test, Panel, PanelTest

load_dotenv()

# ============================================================
# 1. ADMIN SEEDING
# ============================================================
def seed_admin():
    """Create or update admin user from environment variables."""
    db = SessionLocal()
    try:
        admin_username = os.getenv('ADMIN_USERNAME', 'admin')
        admin_password = os.getenv('ADMIN_PASSWORD', 'admin123')

        existing = crud.get_admin_user(db, admin_username)
        if existing:
            print(f"Admin user '{admin_username}' already exists (id={existing.id}).")
        else:
            crud.create_admin_user(db, admin_username, admin_password)
            print(f"Created admin user: {admin_username}")
    finally:
        db.close()

# ============================================================
# 2. LOAD TEST DATA FROM JSON
# ============================================================
def load_test_data_from_json(file_path="test_data.json"):
    """Load test data from JSON.
    Expected format per item:
        {
            "category": "Biochemistry",
            "test_name": "Liver Function Tests",
            "parameter": "ALT (SGPT)",
            "range": "7-56",
            "unit": "U/L",
            "original_reference": "M: 7-56 U/L; F: 7-40 U/L"
        }
    'range' maps to Test.reference_range, 'unit' maps to Test.unit.
    """
    if not os.path.exists(file_path):
        print(f"ERROR: Data file '{file_path}' not found.")
        print("Please run the extraction script first to generate test_data.json.")
        sys.exit(1)

    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Validate required fields
    required_fields = {"category", "test_name", "parameter", "range", "unit"}
    for idx, item in enumerate(data):
        missing = required_fields - set(item.keys())
        if missing:
            print(f"ERROR: Item #{idx} is missing fields: {missing}")
            sys.exit(1)

    print(f"Loaded {len(data)} test records from {file_path}")
    return data

# ============================================================
# 3. HELPER FUNCTIONS (shared)
# ============================================================
def get_or_create_category(db, category_name):
    category = db.query(TestCategory).filter(TestCategory.name == category_name).first()
    if not category:
        category = TestCategory(name=category_name)
        db.add(category)
        db.commit()
        db.refresh(category)
        print(f"Created new category: {category_name}")
    else:
        print(f"Found existing category: {category_name}")
    return category

def get_or_create_panel(db, panel_name):
    panel = db.query(Panel).filter(Panel.name == panel_name).first()
    if not panel:
        panel = Panel(name=panel_name, price=0.0)
        db.add(panel)
        db.commit()
        db.refresh(panel)
        print(f"Created new panel: {panel_name}")
    return panel

def create_test_in_panel(db, category_id, panel_id, parameter, reference_range, unit, price=0.0):
    """Create the parameter as a Test and link it to its Panel, unless it
    already exists (idempotent)."""
    existing = (
        db.query(Test)
        .join(PanelTest, PanelTest.test_id == Test.id)
        .filter(PanelTest.panel_id == panel_id, Test.name == parameter)
        .first()
    )
    if existing:
        print(f"Test already exists: {parameter} (panel #{panel_id})")
        return existing

    new_test = Test(
        name=parameter,
        price=price,
        reference_range=reference_range,
        unit=unit,
        category_id=category_id
    )
    db.add(new_test)
    db.commit()
    db.refresh(new_test)

    sequence = db.query(PanelTest).filter(PanelTest.panel_id == panel_id).count()
    db.add(PanelTest(panel_id=panel_id, test_id=new_test.id, sequence=sequence))
    db.commit()

    print(f"Created new test: {parameter} (panel #{panel_id})")
    return new_test

# ============================================================
# 4. MAIN INSERTION LOGIC
# ============================================================
def seed_tests(test_data):
    db = SessionLocal()
    try:
        print("\n" + "=" * 80)
        print("SEEDING TEST DATA")
        print("=" * 80)

        # Create categories first
        categories = set(item["category"] for item in test_data)
        category_map = {}
        for cat_name in categories:
            cat = get_or_create_category(db, cat_name)
            category_map[cat_name] = cat.id

        # Some generic group names (e.g. "Physical Examination", "Chemical
        # Examination", "Inflammatory Markers") are reused across different
        # categories (Stool vs Urinalysis, Biochemistry vs Stool, etc). Each
        # occurrence must become its OWN panel, so disambiguate the display
        # name with the category whenever a (category, test_name) pair isn't
        # unique on its own.
        group_categories = {}
        for item in test_data:
            group_categories.setdefault(item["test_name"], set()).add(item["category"])

        # Create panels keyed by (category, test_name) so same-named groups
        # in different categories never collide.
        panel_map = {}  # (category, test_name) -> panel_id
        for item in test_data:
            key = (item["category"], item["test_name"])
            if key in panel_map:
                continue
            if len(group_categories[item["test_name"]]) > 1:
                display_name = f"{item['test_name']} ({item['category'].split('/')[0].split(' ')[0]})"
            else:
                display_name = item["test_name"]
            panel = get_or_create_panel(db, display_name)
            panel_map[key] = panel.id

        # Insert each test parameter, linked to its panel
        for idx, data in enumerate(test_data, 1):
            cat_id = category_map[data["category"]]
            panel_id = panel_map[(data["category"], data["test_name"])]
            create_test_in_panel(
                db=db,
                category_id=cat_id,
                panel_id=panel_id,
                parameter=data["parameter"],
                reference_range=data["range"],      # <-- from JSON
                unit=data["unit"],                  # <-- from JSON
                price=0.0
            )
            if idx % 50 == 0:
                print(f"  ... processed {idx} tests")

        print("\n" + "-" * 80)
        print(f"All test data inserted/verified. Total records: {len(test_data)}")
    except Exception as e:
        print(f"Error: {e}")
        db.rollback()
        sys.exit(1)
    finally:
        db.close()

# ============================================================
# 5. VERIFICATION / DISPLAY
# ============================================================
def list_inserted_data():
    db = SessionLocal()
    try:
        print("\n" + "=" * 80)
        print("VERIFICATION OF INSERTED DATA")
        print("=" * 80)

        panels = db.query(Panel).order_by(Panel.name).all()
        for panel in panels:
            tests = panel.tests
            print(f"\n[Panel] {panel.name} ({len(tests)} tests)")
            for test in tests:
                print(f"       - {test.name}: range={test.reference_range}, unit={test.unit}")
    except Exception as e:
        print(f"Verification error: {e}")
    finally:
        db.close()

# ============================================================
# 6. MAIN
# ============================================================
def main():
    print("=" * 80)
    print("LMS DATABASE SEEDING")
    print("=" * 80)

    # Load test data from JSON
    test_data = load_test_data_from_json("test_data.json")

    # Ensure tables exist
    create_tables()

    # Seed admin
    seed_admin()

    # Seed tests
    seed_tests(test_data)

    # Show summary
    list_inserted_data()

    print("\nSeeding completed successfully!")

if __name__ == "__main__":
    main()